# Generated by Django 5.2.10 on 2026-03-04 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('deviceid', models.CharField(max_length=100)),
                ('kwh', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('txtime', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'appliatrixdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deviceid', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devactivity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrackKwh',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deviceid', models.CharField(max_length=50)),
                ('lastkwh', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
            options={
                'db_table': 'trackkwh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceCommandSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ON', 'Switch ON'), ('OFF', 'Switch OFF')], max_length=10)),
                ('scheduled_time', models.DateTimeField()),
                ('executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('devices', models.ManyToManyField(related_name='schedules', to='devices.deviceinfo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='device_schedules', to='organizations.organization')),
            ],
            options={
                'db_table': 'device_command_schedule',
                'managed': True,
            },
        ),
    ]
