# Generated by Django 5.2.10 on 2026-01-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': False},
        ),
    ]
