# Generated by Django 5.2.10 on 2026-05-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceorder',
            name='product_type',
            field=models.CharField(choices=[('appliatrix_board', 'Appliatrix Board')], default='appliatrix_board', max_length=100),
        ),
    ]
