# Generated by Django 5.2.10 on 2026-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('txn_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('transtime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
    ]
