# Generated by Django 5.2.10 on 2026-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say'), ('O', 'Other')], max_length=1)),
                ('household_type', models.CharField(choices=[('M', 'Male headed'), ('F', 'Female headed'), ('C', 'Child headed'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('household_size', models.IntegerField()),
                ('preferred_language', models.CharField(choices=[('EN', 'English'), ('SW', 'Kiswahili'), ('NA', 'Native')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
