# Generated by Django 5.2.10 on 2026-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('EPC', 'Electric pressure cooker'), ('IC', 'Induction cooker'), ('O', 'Other')], max_length=3)),
                ('product_name', models.CharField(max_length=255)),
                ('product_model', models.CharField(max_length=255)),
                ('product_serial_number', models.CharField(max_length=255)),
                ('purchase_mode', models.CharField(choices=[('C', 'Cash'), ('DA', 'Deposit Account'), ('P', 'PAYGO')], max_length=2)),
                ('sales_rep', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('metered', models.BooleanField(default=False)),
                ('type_of_use', models.CharField(choices=[('Domestic', 'Domestic'), ('Business', 'Business'), ('Other', 'Other')], default='Domestic', max_length=10)),
                ('specific_economic_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('location_of_use', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_plan', models.CharField(blank=True, choices=[('Wholesale', 'Wholesale 10,600'), ('Plan_1', 'Plan 1: Deposit 4,500 with weekly payments of 190 for 40 weeks(12,100)'), ('Plan_2', 'Plan 2: Deposit 2,500 with weekly payments of 250 for 48 weeks(14,500)'), ('Retail', 'Retail 12,100')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'sale',
                'managed': False,
            },
        ),
    ]
